### ISSUE TITLE
A command framework?

### ISSUE THREAD

**Issue by AnotherTwinkle** [Zomatree/revolt.py#8]
I was wondering if you'll include a command framework extension with the library in the future (simillar to `discord.py`'s `ext.commands`) or you plan to leave that upto the end user to implement.

**Comment by ppotatoo** [comment]
I’m working on a rough draft of a command framework. I doubt it’ll be similar to the final one, but as far as I know this is planned.

**Comment by AnotherTwinkle** [comment]
hmmm, I see. Thanks.
